name: Trigger auto deployment for xoxnogateway-devnet

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/xoxnogateway-devnet-AutoDeployTrigger-526ec4cb-257c-47e9-99f2-2378dd0bfe5c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xoxno.azurecr.io
          username: ${{ secrets.XOXNOGATEWAYDEVNET_REGISTRY_USERNAME }}
          password: ${{ secrets.XOXNOGATEWAYDEVNET_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xoxno.azurecr.io/xoxnogateway-devnet:${{ github.sha }}
          file: ./Dockerfile.devnet
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.XOXNOGATEWAYDEVNET_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n xoxnogateway-devnet -g XOXNO --server xoxno.azurecr.io --username  ${{ secrets.XOXNOGATEWAYDEVNET_REGISTRY_USERNAME }} --password ${{ secrets.XOXNOGATEWAYDEVNET_REGISTRY_PASSWORD }}
            az containerapp update -n xoxnogateway-devnet -g XOXNO --image xoxno.azurecr.io/xoxnogateway-devnet:${{ github.sha }}
