name: Trigger auto deployment for xoxnogateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/xoxnogateway-AutoDeployTrigger-494b232d-58ea-4e3d-aec6-e2b22952536f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: xoxno.azurecr.io
          username: ${{ secrets.XOXNOGATEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.XOXNOGATEWAY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xoxno.azurecr.io/xoxnogateway:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.XOXNOGATEWAY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n xoxnogateway -g XOXNO --server xoxno.azurecr.io --username  ${{ secrets.XOXNOGATEWAY_REGISTRY_USERNAME }} --password ${{ secrets.XOXNOGATEWAY_REGISTRY_PASSWORD }}
            az containerapp update -n xoxnogateway -g XOXNO --image xoxno.azurecr.io/xoxnogateway:${{ github.sha }}
